[package]

name = "rust-tld"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[dependencies]
rocket = "0.2.6"
rocket_codegen = "0.2.6"
hyper = "0.10"
clippy = {version = "*", optional = true}

[features]
default = []

[profile.release]
lto = true